# Job execution of test-job-2 and deploy-job-3 fails as each job executes on individual instance
# Output of job 1 is not accessible to another job

name: Execution of Multiple Jobs

on: push

jobs:
     build-job-1:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay Program 
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay command
          run: cowsay -f dragon "Run for cover, I am DRAGON...GRrrrr" >> dragon.txt

     test-job-2:
        needs: build-job-1
        runs-on: ubuntu-latest
        steps:
        - name: sleep for 10 seconds
          run: sleep 10

        - name: Test file exists
          run: grep -i "dragon" dragon.txt

     deploy-job-3:
        needs: [build-job-1,test-job-2]
        runs-on: ubuntu-latest
        steps:
        - name: Read file
          run: cat dragon.txt 

        - name: Deploy
          run: echo "Deploying..... ..""

