
name: Execution of Multiple Jobs

on: push

jobs:
     build-job-1:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay Program 
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay command
          run: cowsay -f dragon "Run for cover, I am DRAGON...GRrrrr" >> dragon.txt

        - name: Upload Dragon file
          uses: actions/upload-artifact@v4
          with:
            name: dragon text file
            path: dragon.txt


     test-job-2:
        needs: build-job-1
        runs-on: ubuntu-latest
        steps:
        - name: Download Dragon file
          uses: actions/download-artifact@v4
          with:
            name: dragon text file
            
        - name: Test file exists
          run: grep -i "dragon" dragon.txt

     deploy-job-3:
        needs: [build-job-1,test-job-2]
        runs-on: ubuntu-latest
        steps:
        - name: Download Dragon file
          uses: actions/download-artifact@v4
          with:
            name: dragon text file 

        - name: Read file
          run: cat dragon.txt 

        - name: Deploy
          run: echo "Deploying..... ..""

