name: shell script execution

on: push

jobs:
     shell-script-execution:
                 runs-on: ubuntu-latest
                 steps:
                 - name: Checkout
                   uses: actions/checkout@v4

                 - name: 
                   run: |
                         echo "Shell script execution"
                         sudo apt-get install cowsay -y
                         cowsay -f dragon " I am a dragon and errr" >>dragon.txt
                         grep -i "dragon" dragon.txt      
                         cat dragon.txt
                         ls -ltra
