name: Execution of Multiple Jobs

on: push

jobs:
     build-job-1:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay Program 
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay command
          run: cowsay -f dragon "Run for cover, I am DRAGON...GRrrrr" >> dragon.txt

     test-job-2:
        runs-on: ubuntu-latest
        steps:
        - name: sleep for 10 seconds
          run: sleep 10

        - name: Test file exists
          run: grep -i "dragon" dragon.txt

     deploy-job-3:
        runs-on: ubuntu-latest
        steps:
        - name: Read file
          run: cat dragon.txt 

        - name: Deploy
          run: echo "Deploying..... ..""
