name: Executing via script 

on: push

jobs:
  shell-script:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: List files
       run: ls -alrt

     - name: Exec shell script
       shell: bash
       run: |
          chmod +x myscript.sh   
          ./myscript.sh

